### ISSUE TITLE
Add MIT License and AUTHORS.md documents

### ISSUE THREAD

**Issue by ghost** [hermanjunge/k8s-do-tf#12]
For authors, add name, email, github handle and twitter maybe?

**Comment by 5tefan** [comment]
Looking at some other repos with AUTHORS.md files, it seems prevalent to have a list of names (or alias) each linked to a Github profile. Seems like a good way to respect contributor anonymity if they desire and only one place update if info changes. 

[1] https://github.com/asciidisco/grunt-requirejs/blob/master/AUTHORS.md
[2] https://github.com/django/django/blob/master/AUTHORS
[3] https://github.com/ql-io/ql.io/blob/master/AUTHORS.md

**Comment by ghost** [comment]
@arkanus Hi, do we add your full name, just _Marcos_, or _Arkanus_? Please, let us know via a PR or comment.
