### ISSUE TITLE
Secure etcd access

### ISSUE THREAD

**Issue by ghost** [hermanjunge/k8s-do-tf#2]
Everybody and their dog can access to ETCD. The best path to take is to implement TLS/SSL.

You must observe that the following agents are accesing ETCD:
- `kube-apiserver` in master
- `podmaster` in master, both in `scheduler-elector` as `controller-manager-elector`
- `flannel` in master
- `flannel` in each worker

IIRC, the problem is solved for `kube-apiserver` and `flannel`. I don't know what happens with `podmaster`.

**Comment by 5tefan** [comment]
I've been working on this as a learning exercise and it looks like I've finally gotten it working. I'll create a PR!

**Comment by ghost** [comment]
@5tefan are we good to close this issue then?
