### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by alpe** [hermanjunge/k8s-do-tf#20]
I was wondering what scope do you have in mind with this project?
Are you planning to cover storage, ingress, high availability, helm, etc

**Comment by ghost** [comment]
Nothing in mind. Maybe we should evolve from `Setup a simple Kubernetes cluster in Digital Ocean using Terraform` to something more comprehensive.

What do you propose?

**Comment by DocBradfordSoftware** [comment]
Steps to add Block Storage on DigitalOcean. (Flocker)

**Comment by alpe** [comment]
I've changed my mind a little. The beauty of this project was simplicity. It was easy to setup and understand. I think now it would be better to have a second project with more advanced topics for people who mastered this one. 
I'm very interested in multi master (HA) and persistent storage for a database. Although there are existing projects. For example: https://github.com/Capgemini/kubeform.

**Comment by ghost** [comment]
I like the way you worded it. I wouldn't mind if there is a `k8s-do-TF-advanced` elsewhere, where _we_ say in our README: "OK, This will get you on your feet quickly. If you want advanced features though, please visit this repository!"
