### ISSUE TITLE
Issue on first run

### ISSUE THREAD

**Issue by eugenpirogoff** [hermanjunge/k8s-do-tf#26]
First of all: thank you for such a detailed script I really appreciate it.

Sadly it hangs on DO when

```shell
digitalocean_droplet.k8s_etcd: Provisioning with 'file'...
```
 and errors with 
```shell
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
 I might use it wrong. Do you have any pointers for me? 

<img width="974" alt="screen shot 2017-02-06 at 00 39 44" src="https://cloud.githubusercontent.com/assets/386351/22630979/c80dae5c-ec04-11e6-85fc-96c1c1f15128.png">

Thank you for your work anyway!

**Comment by 5tefan** [comment]
Did you start ssh-agent?

```
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
```

**Comment by eugenpirogoff** [comment]
Yes. ☹️

**Comment by 5tefan** [comment]
Have you added that key to your DO account? 

https://cloud.digitalocean.com/settings/security

**Comment by eugenpirogoff** [comment]
This too. I can deploy my other script, which is a trivial terraform example without any issues.

**Comment by 5tefan** [comment]
Actually, I just ran into this as well trying to test #25 .... hmmm.

**Comment by 5tefan** [comment]
@eugenpirogoff, can you check if this is working for you?

I'm now able to run and haven't made any changes. Seems like a provider (DO) issue.

**Comment by eugenpirogoff** [comment]
@5tefan still the same issue. also changed region to from `nyc` to `fra` did not help.

**Comment by Nepoxx** [comment]
Try changing all the `connection` blocks in `deploy.tf` to:

```
    connection {
      user        = "core"
      private_key = "${file("/path/to/your/private/key")}"
    }
```
