### ISSUE TITLE
Securing network between droplets (RFC)

### ISSUE THREAD

**Issue by Nepoxx** [hermanjunge/k8s-do-tf#29]
Digital Ocean's private networking isn't truly "private", therefore the connection between droplets should ideally be encrypted. I've seen many people setup [tinc](https://www.tinc-vpn.org/) or OpenVPN as well as [droplan](https://github.com/tam7t/droplan) (which does not encrypt but sets up iptable rules such that only traffic from our cluster is accepted).

I'm looking for suggestions/opinions about the best way to go at this. My proposition is to use Tinc since it is much simpler to setup than openVPN and most importantly does not use the "spoke" layout that OpenVPN uses (there is no "one master server", each droplet can communicate to each other directly).

Thoughts?

**Comment by 5tefan** [comment]
coreos/flannel#485 securing flannel
...leading finally to _recently_...
coreos/flannel#637 IPSEC backend, continued 

Not sure what will end up. "[T]he easiest thing is to just secure your traffic at the application layer via TLS (e.g. https). This is no different than if you were running without flannel overlay and just using regular networking." -@eyakubovich

When flannel supports it, we should set it up here. In the meantime, while it requires another layer of configuration, I might defer to this project's original goal of providing a simple starter template, thinking it may be more appropriate as a fork we can link to. 

For implementation, I found [1] for tinc, and [2] maybe?

[1] https://github.com/coreos/flannel/issues/6#issuecomment-127061811
[2] https://github.com/coreos/flannel/issues/6#issuecomment-126904242

**Comment by Nepoxx** [comment]
I agree that a secured flannel would be preferable, however that suggestion is almost a year old and nothing came of it, yet. I'll make a fork with an encrypted flannel using tinc in the meantime as I agree that it would pollute this project/hinder its goal of keeping things simple. That being said, I would suggest adding a note in the readme that the private networking in Digital Ocean is not truly "private" and that inter-droplet communication can be intercepted and should not be trusted.
