### ISSUE TITLE
Move repository to its own organization

### ISSUE THREAD

**Issue by ghost** [hermanjunge/k8s-do-tf#40]
This repository has gained some usefulness within the community. Unfortunately I, Herman, cannot commit to maintain it. Hence, I'm moving it to a new organization.

https://github.com/kubernetes-digitalocean-terraform

**Comment by ghost** [comment]
Hi @5tefan, please acknowledge this change.

**Comment by 5tefan** [comment]
@hermanjunge Ok with me!

**Comment by ghost** [comment]
@5tefan Check your email, I've sent you an invite to become admin in the org.

**Comment by ghost** [comment]
Oh! You saw it already. Cool 😄
