### ISSUE TITLE
Using kubeadm 

### ISSUE THREAD

**Issue by srolel** [hermanjunge/k8s-do-tf#49]
I'm happy with being able to set my cluster on digital ocean with this, so thanks for sharing :)

Is there a specific reason kubeadm is not used to set up the cluster?

**Comment by 5tefan** [comment]
This project predates kubeadm. 

First impressions of kubeadm:

- kubeadm supports cluster upgrades. I'm not sure how that would work with Terraform (but this is a problem with the current configuration).
- kubeadm isn't supported on (ContainerLinux/CoreOS), not sure how important CoreOS is for users of this config.

Assuming I haven't overlooked something major, I think it would be net advantageous to outsource the k8s setup to a common project which is what kubeadm attempts to be. 

If someone wants to submit a PR, I think the response would be appreciative. Checked, kubeadm appears to be compatible with using custom cloud-controller-managers (#39).

**Comment by srolel** [comment]
I got something working, the main difference being that kubeadm sets up etcd on the master, instead of a separate VM. They are working on a HA setup where that can be changed. I did manage to set up kubeadm and a working cluster on CoreOS despite not having an official package.

**Comment by 5tefan** [comment]
Seems ok to me, removing dedicated etcd host was asked for in #24. 

Hmm, kubernetes/kubeadm#300 is relevant.

**Comment by srolel** [comment]
Yeah, that's what I used to set up.
