### ISSUE TITLE
etcd2 not loading properly after reboot

### ISSUE THREAD

**Issue by kyv** [hermanjunge/k8s-do-tf#52]
I have an issue where etcd2 is not loading correctly after reboot. The service starts but but other services are not able to connect. `kubectl` for example:

The connection to the server xxx.xxx.xxx.xx:xxxx was refused - did you specify the right host or port?

If I ssh into the etcd node and restart it manually with `systemctl restart etcd2` after a few minutes `kubectl get pods` show my running pods.

This is possibly related to [this issue](https://github.com/coreos/bugs/issues/438) where the workaround is to add a drop in to the cloud-config. When I have time to do some test deployments I can test that, but meanwhile has anyone else run into this problem?

**Comment by kyv** [comment]
This may be due to etcd2 unit being enabled in the OS.

 https://github.com/kubernetes-digitalocean-terraform/kubernetes-digitalocean-terraform/blob/3ecf45da85f9ff2bb4c1d347f44583b5cd36622d/deploy.tf#L133

Problem seems to be resolved by disabling the unit.

**Comment by sonamsamdupkhangsar** [comment]
The stable version of coreos image does not include etcd2.  It seems they moved to etcd3.  Is there a   updated version that uses the etcd3 with config transpilar?
I have been looking at this https://github.com/ihcsim/kubernetes-terraform-secured but seems a overkill for my need as I like this repo which is much simpler.

**Comment by kyv** [comment]
Yes recent changes in coreos seems to have obsoleted much of this repo. Personally I am working on top of #51 now, which, with a few modifications, can get you up and running. I'm not sure what the maintainers here are planning, though.

**Comment by sonamsamdupkhangsar** [comment]
@kyv Can you share your updates?  I would like to check it out

**Comment by kyv** [comment]
Here you go:
https://github.com/kyv/kubernetes-digitalocean-terraform/tree/kubeadm

Be aware that I've made my own enhancments which you may or may not want. I've put some information about that [here](https://github.com/kyv/kubernetes-digitalocean-terraform/tree/kubeadm).

**Comment by fsegouin** [comment]
@kyv Trying to use your fork and I had an issue regarding an hardcoded value in your `deploy.tf` file. If we specify less than 3 workers, the following will fail:

```
WORKER_HOST_1 = "${digitalocean_droplet.k8s_worker.0.ipv4_address_private}"
          WORKER_HOST_2 = "${digitalocean_droplet.k8s_worker.1.ipv4_address_private}"
          WORKER_HOST_3 = "${digitalocean_droplet.k8s_worker.2.ipv4_address_private}"
```

**Comment by bhcleek** [comment]
Closing because kubeadm is now used to configure etcd.
