### ISSUE TITLE
Typhoon tutorial vs this repo

### ISSUE THREAD

**Issue by kamilgregorczyk** [hermanjunge/k8s-do-tf#53]
Hi, what's the difference between this tutorial and this tutorial? https://typhoon.psdn.io/digital-ocean/

I'm trying to find a way to setup a proper, fully prod ready Kubernetes cluster on digital ocean and these two solutions seem to be the easiest ones. DigitalOcean is almost 2x cheaper than GCP which is great for my needs but it doesn't offer one click Kubernetes installation

**Comment by vrybas** [comment]
@kamilgregorczyk did you set up Kubernetes cluster on DO? Which tutorial did you follow in the end? How it's working out for you so far?

**Comment by kamilgregorczyk** [comment]
I haven't but Im planning to and I'm trying to find a proper solution. I'm not a Devops guy, I just want a secure Kubernetes cluster which doesn't cost a fortune. This repo seems to be doing a better job, less configuration etc. than the original terraform tutorial but in the other hand I'm not fully confident if it's actually a secure cluster.

**Comment by bhcleek** [comment]
As far as the security of the cluster configured by this project, we strive to set up the cluster securely. If you find any problems, please let us know.

The link to the other tutorial gives a 404.

**Comment by kamilgregorczyk** [comment]
Ah, they changed the link: https://typhoon.psdn.io/cl/digital-ocean/
